version: "3.3"

services:
    fastapi:
        image: fz-server:latest
        container_name: fastapi 
        env_file:
            - .env
        build:
            context: "./"
            dockerfile: "Dockerfile"
        volumes:
        - ./src:/main
        command: sleep infinity
        restart: unless-stopped

    db:
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_DB: fz
            POSTGRES_USER: ${DB_USERNAME:-test} 
            POSTGRES_PASSWORD: ${DB_PASSWORD:-test}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-hi@beeeeemo.dev}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-test} 
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "15432:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    db-data:
    pgadmin-data: